v2.17.0 + database backup

diff --git a/image/service/backup/assets/tool/piwik-restore b/image/service/backup/assets/tool/piwik-restore
--- a/image/service/backup/assets/tool/piwik-restore
+++ b/image/service/backup/assets/tool/piwik-restore
@@ -1,9 +1,34 @@
 #!/bin/bash -e
 
-# Usage: /sbin/mail-restore file
-file=$1
+# Usage: /sbin/piwik-restore file [file] ...
 backupPath="/data/backup"
+backupFileSuffix="-piwik.tar.gz"
+backupDbSuffix="-piwik-db.tar.gz"
+databaseFile="database.sql"
 
-tar -xzf $backupPath/$file -C /
+for file in "$@"
+do
+    echo "Processing file $file"
+
+    if $(echo "$file" | grep -q -e "$backupFileSuffix"); then
+        echo "Restore piwik files"
+        tar -xvzf $backupPath/$file -C /
+        echo "done :)"
+    elif $(echo "$file" | grep -q -e "$backupDbSuffix"); then
+        echo "Restore piwik database"
+        . /container/service/backup/assets/tool/piwik-get-db-params
+
+        rm -rf $databaseFile || true
+        tar -xvzf $backupPath/$file
+
+        mysql -u $databaseUser -p$databasePassword --host $host $database < $databaseFile
+
+        rm -rf $databaseFile
+
+        echo "done :)"
+    else
+      echo "Error: Unknown file type"
+    fi
+done
 
 exit 0
